defmodule MembaWeb.Admin.ClubsLive.Index do
  use MembaWeb, :live_view

  alias Memba.Membership
  alias MembaWeb.Admin.ClubSlugForm

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    clubs = Membership.list_clubs()

    {:ok,
     socket
     |> assign(:club_form, ClubSlugForm.to_form())
     |> assign(:club_slug_autogenerated?, true)
     |> assign_clubs(clubs)}
  end

  @impl Phoenix.LiveView
  def handle_event("suggest_slug", %{"club" => club_params} = params, socket) do
    target = Map.get(params, "_target", [])

    {:noreply, assign_club_form(socket, club_params, target)}
  end

  @impl Phoenix.LiveView
  def handle_event("create_club", %{"club" => club_params}, socket) do
    attrs =
      club_params
      |> Map.take(["name", "slug"])
      |> Map.put("club_id", Memba.ID.generate(:club))

    case Membership.create_club(attrs, consistency: :strong) do
      :ok ->
        {:noreply, assign_club_created(socket)}

      {:ok, _result} ->
        {:noreply, assign_club_created(socket)}

      {:error, reason} ->
        {:noreply,
         socket
         |> put_flash(:error, "Could not create club: #{format_reason(reason)}")
         |> assign(:club_form, ClubSlugForm.to_form(club_params))
         |> assign(:club_slug_autogenerated?, false)}
    end
  end

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <Layouts.admin flash={@flash} current_identity={@current_identity} active={:clubs}>
      <main id="clubs-index" data-admin-page="clubs" class="space-y-6 p-6">
        <p class="sr-only">Memba staff operations</p>
        <.admin_page_header title="Clubs">
          <:actions>
            <a
              id="clubs-index-new-club-action"
              href="#new-club-form"
              class="inline-flex h-11 items-center justify-center rounded-lg border border-[#1f4842] bg-[#1f4842] px-4 text-sm font-semibold text-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:bg-[#15201c] hover:shadow-md"
            >
              <.icon name="hero-plus" class="mr-2 size-4 bg-current" /> New club
            </a>
          </:actions>
        </.admin_page_header>

        <p id="clubs-summary-total" class="text-sm font-medium text-[#4b5a55]">
          Showing {@club_count} {if @club_count == 1, do: "club", else: "clubs"}.
        </p>

        <details
          id="clubs-create-card"
          class="rounded-xl border border-[#e0ddd4] bg-white p-5 shadow-sm open:ring-2 open:ring-[#e6ece4]"
          open
        >
          <summary class="cursor-pointer list-none text-base font-semibold text-[#15201c]">
            Create a club
            <span class="ml-2 text-sm font-normal text-[#7d877f]">
              The slug is suggested from the club name.
            </span>
          </summary>

          <.form
            for={@club_form}
            id="new-club-form"
            aria-label="Create a club"
            class="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] lg:items-end"
            phx-change="suggest_slug"
            phx-submit="create_club"
          >
            <div>
              <.input
                field={@club_form[:name]}
                id="club-name-input"
                label="Name"
                aria-label="Club name"
                required
              />
            </div>
            <div>
              <.input
                field={@club_form[:slug]}
                id="club-slug-input"
                label="Slug"
                aria-label="Club slug"
                maxlength={ClubSlugForm.max_length()}
                required
              />
              <p id="club-slug-help" class="mt-1 text-xs text-[#7d877f]">
                Use lowercase letters, numbers, and hyphens.
              </p>
            </div>
            <.button
              id="create-club-button"
              type="submit"
              aria-label="Create club"
            >
              Create club
            </.button>
          </.form>
        </details>

        <.admin_toolbar
          id="clubs-toolbar"
          summary_label="All"
          summary_count={@club_count}
        />

        <.admin_table_card
          id="clubs-directory-card"
          title="Club directory"
          description="Sorted by club name for stable staff scanning and browser automation."
        >
          <div class="overflow-x-auto">
            <table id="clubs-table" aria-label="Club records" class="min-w-full text-left text-sm">
              <thead class="bg-[#efede8] text-xs font-bold uppercase tracking-[0.08em] text-[#7d877f]">
                <tr>
                  <th scope="col" class="px-4 py-3">Club</th>
                  <th scope="col" class="px-4 py-3">Slug</th>
                  <th scope="col" class="px-4 py-3">Identifier</th>
                  <th scope="col" class="px-4 py-3">Open</th>
                </tr>
              </thead>
              <tbody
                id="clubs"
                aria-label="Clubs"
                class="divide-y divide-[#e6e3dc]"
                phx-update="stream"
              >
                <tr id="clubs-empty" class="hidden only:table-row">
                  <td colspan="4" class="px-4 py-6 text-center text-sm text-[#7d877f]">
                    No clubs yet.
                  </td>
                </tr>
                <tr
                  :for={{dom_id, club} <- @streams.clubs}
                  id={dom_id}
                  data-testid="club-row"
                  data-club-id={club.club_id}
                  data-club-name={club.name}
                  data-club-slug={club.slug}
                  aria-label={"Club #{club.name}"}
                  class="transition-colors hover:bg-[#fbfaf8]"
                >
                  <td class="px-4 py-3.5">
                    <.admin_identity_cell
                      initials={club_initials(club.name)}
                      title={club.name}
                      subtitle="Club record"
                      link={~p"/admin/clubs/#{club.club_id}"}
                      link_id={"club-link-#{club.club_id}"}
                      testid="club-link"
                      aria_label={"Open club #{club.name}"}
                    />
                  </td>
                  <td class="px-4 py-3.5">
                    <span class="rounded-full bg-[#f7f6f3] px-2.5 py-1 font-mono text-xs text-[#4b5a55]">
                      {club.slug}
                    </span>
                  </td>
                  <td class="px-4 py-3.5 font-mono text-xs text-[#7d877f]">{club.club_id}</td>
                  <td class="px-4 py-3.5">
                    <.link
                      navigate={~p"/admin/clubs/#{club.club_id}"}
                      class="inline-flex items-center rounded-full border border-[#d6d2c8] px-3 py-1.5 text-xs font-semibold text-[#4b5a55] transition duration-200 hover:-translate-y-0.5 hover:border-[#1f4842] hover:text-[#15201c]"
                    >
                      Open
                    </.link>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </.admin_table_card>
      </main>
    </Layouts.admin>
    """
  end

  defp format_reason(reason), do: reason |> inspect() |> String.replace("_", " ")

  defp assign_club_created(socket) do
    clubs = Membership.list_clubs()

    socket
    |> put_flash(:info, "Club created")
    |> assign(:club_form, ClubSlugForm.to_form())
    |> assign(:club_slug_autogenerated?, true)
    |> assign_clubs(clubs, reset: true)
  end

  defp assign_clubs(socket, clubs, stream_opts \\ []) do
    stream_opts = Keyword.merge([dom_id: &"club-#{&1.club_id}"], stream_opts)

    socket
    |> assign(:club_count, length(clubs))
    |> stream(:clubs, clubs, stream_opts)
  end

  defp assign_club_form(socket, club_params, target) do
    {club_params, slug_autogenerated?} =
      ClubSlugForm.suggest_params(club_params, target, socket.assigns.club_slug_autogenerated?)

    socket
    |> assign(:club_form, ClubSlugForm.to_form(club_params))
    |> assign(:club_slug_autogenerated?, slug_autogenerated?)
  end

  defp club_initials(name) when is_binary(name) do
    name
    |> String.split(~r/\s+/, trim: true)
    |> Enum.take(2)
    |> Enum.map(&String.first/1)
    |> Enum.join()
    |> String.upcase()
    |> case do
      "" -> "CL"
      initials -> initials
    end
  end

  defp club_initials(_name), do: "CL"
end
