defmodule MembaWeb.Admin.ClubsLive.Index do
  use MembaWeb, :live_view

  alias Memba.Membership
  alias Memba.Membership.Slug

  @empty_club %{"name" => "", "slug" => ""}

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    clubs = Membership.list_clubs()

    {:ok,
     socket
     |> assign(:club_form, to_form(@empty_club, as: :club))
     |> assign(:club_slug_autogenerated?, true)
     |> assign_clubs(clubs)}
  end

  @impl Phoenix.LiveView
  def handle_event("suggest_slug", %{"club" => club_params} = params, socket) do
    target = Map.get(params, "_target", [])

    {:noreply, assign_club_form(socket, club_params, target)}
  end

  @impl Phoenix.LiveView
  def handle_event("create_club", %{"club" => club_params}, socket) do
    attrs =
      club_params
      |> Map.take(["name", "slug"])
      |> Map.put("club_id", Memba.ID.generate(:club))

    case Membership.create_club(attrs, consistency: :strong) do
      :ok ->
        {:noreply, assign_club_created(socket)}

      {:ok, _result} ->
        {:noreply, assign_club_created(socket)}

      {:error, reason} ->
        {:noreply,
         socket
         |> put_flash(:error, "Could not create club: #{format_reason(reason)}")
         |> assign(:club_form, to_form(club_params, as: :club))
         |> assign(:club_slug_autogenerated?, false)}
    end
  end

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <Layouts.admin flash={@flash}>
      <main id="clubs-index" data-admin-page="clubs" class="mx-auto max-w-7xl space-y-6 p-6">
        <section class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div class="space-y-2">
            <p class="text-sm font-semibold uppercase tracking-wide text-[#7d877f]">
              Memba staff operations
            </p>
            <h1 class="text-3xl font-bold tracking-tight text-[#15201c]">Clubs</h1>
            <p class="max-w-3xl text-[#4b5a55]">
              Create club records, keep their public slug clear, and open a club to manage its
              people and memberships.
            </p>
          </div>
          <a
            id="clubs-index-new-club-action"
            href="#new-club-form"
            class="inline-flex items-center justify-center rounded-full border border-[#1f4842] bg-[#1f4842] px-4 py-2 text-sm font-semibold text-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:bg-[#15201c] hover:shadow-md"
          >
            New club
          </a>
        </section>

        <section
          id="clubs-summary"
          aria-label="Club operations summary"
          class="grid gap-4 md:grid-cols-2"
        >
          <article class="rounded-2xl border border-[#e6e3dc] bg-white p-5 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-wide text-[#7d877f]">Club records</p>
            <p id="clubs-summary-total" class="mt-3 text-3xl font-bold tracking-tight text-[#15201c]">
              {@club_count}
            </p>
            <p class="mt-1 text-sm text-[#4b5a55]">
              Total projected clubs in the staff directory.
            </p>
          </article>

          <article class="rounded-2xl border border-[#e6e3dc] bg-white p-5 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-wide text-[#7d877f]">
              Operations model
            </p>
            <p class="mt-3 text-lg font-semibold text-[#15201c]">Clubs stay distinct</p>
            <p class="mt-1 text-sm text-[#4b5a55]">
              Open a club record for club facts, person records, and memberships.
            </p>
          </article>
        </section>

        <section
          id="clubs-create-card"
          class="rounded-2xl border border-[#e6e3dc] bg-white p-5 shadow-sm"
        >
          <div class="flex flex-col gap-1">
            <h2 class="text-lg font-semibold text-[#15201c]">Create a club</h2>
            <p class="text-sm text-[#7d877f]">
              The slug is suggested from the club name and can still be edited before creation.
            </p>
          </div>

          <.form
            for={@club_form}
            id="new-club-form"
            aria-label="Create a club"
            class="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] lg:items-end"
            phx-change="suggest_slug"
            phx-submit="create_club"
          >
            <div>
              <.input
                field={@club_form[:name]}
                id="club-name-input"
                label="Name"
                aria-label="Club name"
                required
              />
            </div>
            <div>
              <.input
                field={@club_form[:slug]}
                id="club-slug-input"
                label="Slug"
                aria-label="Club slug"
                maxlength={Slug.max_length()}
                required
              />
              <p id="club-slug-help" class="mt-1 text-xs text-[#7d877f]">
                Suggested from the name. Use lowercase letters, numbers, and hyphens.
              </p>
            </div>
            <.button
              id="create-club-button"
              type="submit"
              aria-label="Create club"
              class="inline-flex items-center justify-center rounded-full border border-[#1f4842] bg-[#1f4842] px-4 py-2 text-sm font-semibold text-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:bg-[#15201c] hover:shadow-md"
            >
              Create club
            </.button>
          </.form>
        </section>

        <section
          id="clubs-directory-card"
          class="overflow-hidden rounded-2xl border border-[#e6e3dc] bg-white shadow-sm"
        >
          <div class="border-b border-[#e6e3dc] p-5">
            <h2 class="text-lg font-semibold text-[#15201c]">Club directory</h2>
            <p class="mt-1 text-sm text-[#7d877f]">
              Sorted by club name for stable staff scanning and browser automation.
            </p>
          </div>

          <div class="overflow-x-auto">
            <table
              id="clubs-table"
              aria-label="Club records"
              class="min-w-full divide-y divide-[#e6e3dc] text-left text-sm"
            >
              <thead class="bg-[#f7f6f3] text-xs font-semibold uppercase tracking-wide text-[#7d877f]">
                <tr>
                  <th scope="col" class="px-4 py-3">Club</th>
                  <th scope="col" class="px-4 py-3">Slug</th>
                  <th scope="col" class="px-4 py-3">Identifier</th>
                  <th scope="col" class="px-4 py-3">Open</th>
                </tr>
              </thead>
              <tbody
                id="clubs"
                aria-label="Clubs"
                class="divide-y divide-[#e6e3dc]"
                phx-update="stream"
              >
                <tr id="clubs-empty" class="hidden only:table-row">
                  <td colspan="4" class="px-4 py-6 text-center text-sm text-[#7d877f]">
                    No clubs yet.
                  </td>
                </tr>
                <tr
                  :for={{dom_id, club} <- @streams.clubs}
                  id={dom_id}
                  data-testid="club-row"
                  data-club-id={club.club_id}
                  data-club-name={club.name}
                  data-club-slug={club.slug}
                  aria-label={"Club #{club.name}"}
                >
                  <td class="px-4 py-4">
                    <div class="flex items-center gap-3">
                      <div class="flex size-10 shrink-0 items-center justify-center rounded-full bg-[#e6ece4] text-xs font-bold text-[#1f4842]">
                        {club_initials(club.name)}
                      </div>
                      <div>
                        <.link
                          id={"club-link-#{club.club_id}"}
                          navigate={~p"/admin/clubs/#{club.club_id}"}
                          data-testid="club-link"
                          aria-label={"Open club #{club.name}"}
                          class="font-semibold text-[#1f4842] transition duration-200 hover:text-[#15201c]"
                        >
                          {club.name}
                        </.link>
                        <p class="mt-1 text-xs text-[#7d877f]">Club record</p>
                      </div>
                    </div>
                  </td>
                  <td class="px-4 py-4">
                    <span class="rounded-full bg-[#f7f6f3] px-2.5 py-1 font-mono text-xs text-[#4b5a55]">
                      {club.slug}
                    </span>
                  </td>
                  <td class="px-4 py-4 font-mono text-xs text-[#7d877f]">{club.club_id}</td>
                  <td class="px-4 py-4">
                    <.link
                      navigate={~p"/admin/clubs/#{club.club_id}"}
                      class="inline-flex items-center rounded-full border border-[#d6d2c8] px-3 py-1.5 text-xs font-semibold text-[#4b5a55] transition duration-200 hover:-translate-y-0.5 hover:border-[#1f4842] hover:text-[#15201c]"
                    >
                      Open
                    </.link>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </Layouts.admin>
    """
  end

  defp format_reason(reason), do: reason |> inspect() |> String.replace("_", " ")

  defp assign_club_created(socket) do
    clubs = Membership.list_clubs()

    socket
    |> put_flash(:info, "Club created")
    |> assign(:club_form, to_form(@empty_club, as: :club))
    |> assign(:club_slug_autogenerated?, true)
    |> assign_clubs(clubs, reset: true)
  end

  defp assign_clubs(socket, clubs, stream_opts \\ []) do
    stream_opts = Keyword.merge([dom_id: &"club-#{&1.club_id}"], stream_opts)

    socket
    |> assign(:club_count, length(clubs))
    |> stream(:clubs, clubs, stream_opts)
  end

  defp assign_club_form(socket, club_params, target) do
    slug_autogenerated? =
      case target do
        ["club", "slug"] -> blank?(Map.get(club_params, "slug"))
        [] -> blank?(Map.get(club_params, "slug"))
        _target -> socket.assigns.club_slug_autogenerated?
      end

    club_params =
      if slug_autogenerated? do
        Map.put(club_params, "slug", Slug.default_from_name(Map.get(club_params, "name", "")))
      else
        Map.put_new(club_params, "slug", "")
      end

    socket
    |> assign(:club_form, to_form(club_params, as: :club))
    |> assign(:club_slug_autogenerated?, slug_autogenerated?)
  end

  defp blank?(value) when is_binary(value), do: value == ""
  defp blank?(_value), do: true

  defp club_initials(name) when is_binary(name) do
    name
    |> String.split(~r/\s+/, trim: true)
    |> Enum.take(2)
    |> Enum.map(&String.first/1)
    |> Enum.join()
    |> String.upcase()
    |> case do
      "" -> "CL"
      initials -> initials
    end
  end

  defp club_initials(_name), do: "CL"
end
