defmodule MembaWeb.Admin.RequestsLive.Index do
  use MembaWeb, :live_view

  alias Memba.Onboarding
  alias Memba.Onboarding.Request
  alias MembaWeb.Admin.ClubSlugForm

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    requests = Onboarding.list_active_requests()

    socket =
      socket
      |> assign(:rejecting_request, nil)
      |> assign(:rejection_form, nil)
      |> assign(:converting_request, nil)
      |> assign(:conversion_form, nil)
      |> assign(:conversion_slug_autogenerated?, true)
      |> assign(:conversion_slug_feedback, ClubSlugForm.feedback(nil, ""))
      |> assign(:inactive_conversion_request_id, nil)
      |> assign_active_requests(requests)

    {:ok, socket}
  end

  @impl Phoenix.LiveView
  def handle_params(params, _uri, socket) do
    case socket.assigns.live_action do
      :convert ->
        {:noreply, assign_conversion_from_params(socket, Map.get(params, "request_id"))}

      _index ->
        {:noreply,
         socket
         |> clear_conversion()
         |> assign(:inactive_conversion_request_id, nil)}
    end
  end

  @impl Phoenix.LiveView
  def handle_event("start_rejection", %{"request-id" => request_id}, socket) do
    case active_request(request_id) do
      %Request{} = request ->
        {:noreply,
         socket
         |> clear_conversion()
         |> assign(:rejecting_request, request)
         |> assign_rejection_form(Onboarding.change_rejection(request))}

      nil ->
        {:noreply, request_no_longer_active(socket)}
    end
  end

  def handle_event("cancel_rejection", _params, socket) do
    {:noreply, clear_rejection(socket)}
  end

  def handle_event(
        "reject_request",
        params,
        %{assigns: %{rejecting_request: %Request{} = request}} = socket
      ) do
    attrs = Map.get(params, "rejection", %{})

    case Onboarding.reject_request(request.request_id, attrs,
           staff_email: current_staff_email(socket)
         ) do
      {:ok, %Request{} = rejected_request} ->
        {:noreply,
         socket
         |> clear_rejection()
         |> decrement_active_request_count()
         |> stream_delete(:active_requests, rejected_request)
         |> put_flash(:info, "Rejected request for #{rejected_request.requested_club_name}.")}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign_rejection_form(socket, changeset)}

      {:error, _reason} ->
        {:noreply, request_no_longer_active(socket)}
    end
  end

  def handle_event("reject_request", _params, socket) do
    {:noreply, request_no_longer_active(socket)}
  end

  def handle_event("start_conversion", %{"request-id" => request_id}, socket) do
    case active_request(request_id) do
      %Request{} = request ->
        params = conversion_params_from_request(request)

        {:noreply,
         socket
         |> clear_rejection()
         |> assign(:converting_request, request)
         |> assign(:conversion_slug_autogenerated?, true)
         |> assign_conversion_form(params)}

      nil ->
        {:noreply, request_no_longer_active(socket)}
    end
  end

  def handle_event("suggest_conversion_slug", %{"club" => club_params} = params, socket) do
    target = Map.get(params, "_target", [])

    {:noreply, assign_conversion_form(socket, club_params, target)}
  end

  def handle_event("cancel_conversion", _params, socket) do
    {:noreply, push_patch(socket, to: ~p"/admin/requests")}
  end

  def handle_event(
        "convert_request",
        %{"club" => club_params},
        %{assigns: %{converting_request: %Request{} = request}} = socket
      ) do
    feedback = ClubSlugForm.feedback(nil, Map.get(club_params, "slug"))

    if feedback.valid do
      case Onboarding.convert_request_to_club(request.request_id, club_params,
             staff_email: current_staff_email(socket)
           ) do
        {:ok, conversion} ->
          {:noreply, assign_request_converted(socket, conversion)}

        {:error, %Ecto.Changeset{} = changeset} ->
          {:noreply,
           socket
           |> put_flash(:error, "Could not convert request: #{format_reason(changeset)}")
           |> assign_conversion_form(club_params, ["club", "slug"])}

        {:error, reason} when reason in [:not_active, :not_found] ->
          {:noreply, request_no_longer_active(socket)}

        {:error, reason} ->
          {:noreply,
           socket
           |> put_flash(:error, "Could not convert request: #{format_reason(reason)}")
           |> assign_conversion_form(club_params, ["club", "slug"])}
      end
    else
      {:noreply,
       socket
       |> put_flash(:error, "Choose a valid and available slug before converting this request.")
       |> assign_conversion_form(club_params, ["club", "slug"])}
    end
  end

  def handle_event("convert_request", _params, socket) do
    {:noreply, request_no_longer_active(socket)}
  end

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <Layouts.admin flash={@flash} current_identity={@current_identity} active={:requests}>
      <main id="admin-requests-index" data-admin-page="requests" class="space-y-6 p-6">
        <.admin_page_header
          eyebrow="Requests"
          title="Requests"
          description="Review account requests from club organisers before creating clubs, memberships, or sign-in access."
        />

        <section
          id="admin-requests-summary"
          aria-label="Active request summary"
          class="grid gap-4 md:grid-cols-3"
        >
          <article class="rounded-xl border border-[#e0ddd4] bg-white p-5 shadow-sm">
            <p class="text-xs font-bold uppercase tracking-[0.08em] text-[#7d877f]">
              Active requests
            </p>
            <p
              id="admin-requests-active-count"
              class="mt-3 text-3xl font-bold tracking-tight text-[#15201c]"
            >
              {@active_request_count}
            </p>
            <p class="mt-1 text-sm text-[#4b5a55]">Awaiting Memba staff review.</p>
          </article>

          <article class="rounded-xl border border-[#e0ddd4] bg-white p-5 shadow-sm">
            <p class="text-xs font-bold uppercase tracking-[0.08em] text-[#7d877f]">
              Approval model
            </p>
            <p class="mt-3 text-lg font-semibold text-[#15201c]">Staff approved</p>
            <p class="mt-1 text-sm text-[#4b5a55]">
              Public requests do not create clubs or sending access.
            </p>
          </article>

          <article class="rounded-xl border border-[#e0ddd4] bg-white p-5 shadow-sm">
            <p class="text-xs font-bold uppercase tracking-[0.08em] text-[#7d877f]">
              Next action
            </p>
            <p class="mt-3 text-lg font-semibold text-[#15201c]">Reject or convert</p>
            <p class="mt-1 text-sm text-[#4b5a55]">
              Each active request has triage actions for staff review.
            </p>
          </article>
        </section>

        <.admin_toolbar
          id="admin-requests-toolbar"
          summary_label="Active"
          summary_count={@active_request_count}
        />

        <section
          :if={@rejecting_request}
          id={"reject-request-panel-#{@rejecting_request.request_id}"}
          data-testid="reject-request-panel"
          class="rounded-xl border border-[#d6d2c8] bg-white p-5 shadow-sm"
        >
          <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div class="space-y-2">
              <p class="text-xs font-bold uppercase tracking-[0.08em] text-[#7a5416]">
                Reject request
              </p>
              <h2 class="text-xl font-semibold text-[#15201c]">
                {@rejecting_request.requested_club_name}
              </h2>
              <p class="text-sm leading-6 text-[#4b5a55]">
                Capture internal notes before removing this request from the active inbox. The
                requester will not receive an email.
              </p>
              <dl class="grid gap-3 text-sm sm:grid-cols-2">
                <div>
                  <dt class="font-medium text-[#7d877f]">Requester</dt>
                  <dd class="mt-1 text-[#15201c]">
                    {@rejecting_request.requester_name}
                  </dd>
                </div>
                <div>
                  <dt class="font-medium text-[#7d877f]">Email</dt>
                  <dd class="mt-1 text-[#15201c]">
                    {@rejecting_request.requester_email}
                  </dd>
                </div>
              </dl>
            </div>

            <.form
              for={@rejection_form}
              id={"reject-request-form-#{@rejecting_request.request_id}"}
              phx-submit="reject_request"
              aria-label={"Reject request for #{@rejecting_request.requested_club_name}"}
              class="w-full max-w-xl space-y-4"
            >
              <.input
                field={@rejection_form[:internal_rejection_notes]}
                id={"reject-request-notes-#{@rejecting_request.request_id}"}
                label="Internal rejection notes"
                type="textarea"
                rows="4"
                placeholder="Why is Memba not a fit for this request?"
                required
              />
              <p class="text-xs leading-5 text-[#7d877f]">
                Internal notes are stored for staff audit only and are not sent to the requester.
              </p>
              <div class="flex flex-wrap justify-end gap-2">
                <.button
                  id={"cancel-reject-request-#{@rejecting_request.request_id}"}
                  type="button"
                  phx-click="cancel_rejection"
                  variant="secondary"
                >
                  Cancel
                </.button>
                <.button
                  id={"confirm-reject-request-#{@rejecting_request.request_id}"}
                  type="submit"
                  variant="danger"
                >
                  Reject request
                </.button>
              </div>
            </.form>
          </div>
        </section>

        <section
          :if={@converting_request}
          id={"convert-request-panel-#{@converting_request.request_id}"}
          data-testid="convert-request-panel"
          class="rounded-xl border border-[#d6d2c8] bg-white p-5 shadow-sm"
        >
          <div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
            <div class="space-y-2">
              <p class="text-xs font-bold uppercase tracking-[0.08em] text-[#1f4842]">
                Prepare conversion
              </p>
              <h2 class="text-xl font-semibold text-[#15201c]">
                {@converting_request.requested_club_name}
              </h2>
              <p class="text-sm leading-6 text-[#4b5a55]">
                Review the requested club details and confirm the slug before creating a club,
                first member, and welcome sign-in link.
              </p>
              <dl class="grid gap-3 text-sm sm:grid-cols-2">
                <div>
                  <dt class="font-medium text-[#7d877f]">Requester</dt>
                  <dd class="mt-1 text-[#15201c]">
                    {@converting_request.requester_name}
                  </dd>
                </div>
                <div>
                  <dt class="font-medium text-[#7d877f]">Email</dt>
                  <dd class="mt-1 text-[#15201c]">
                    {@converting_request.requester_email}
                  </dd>
                </div>
              </dl>
            </div>

            <.form
              for={@conversion_form}
              id={"convert-request-form-#{@converting_request.request_id}"}
              phx-change="suggest_conversion_slug"
              phx-submit="convert_request"
              aria-label={"Prepare conversion for #{@converting_request.requested_club_name}"}
              class="w-full max-w-2xl space-y-4"
            >
              <.input
                field={@conversion_form[:name]}
                id={"convert-request-club-name-#{@converting_request.request_id}"}
                label="Club name"
                aria-label="Club name"
                required
              />
              <div>
                <.input
                  field={@conversion_form[:slug]}
                  id={"convert-request-club-slug-#{@converting_request.request_id}"}
                  label="Slug"
                  aria-label="Club slug"
                  aria-describedby={"convert-request-club-slug-help-#{@converting_request.request_id} convert-request-club-slug-feedback-#{@converting_request.request_id}"}
                  aria-invalid={@conversion_slug_feedback.status in ["invalid", "taken"]}
                  maxlength={ClubSlugForm.max_length()}
                  required
                />
                <p
                  id={"convert-request-club-slug-help-#{@converting_request.request_id}"}
                  class="mt-1 text-xs text-[#7d877f]"
                >
                  Uses the same lowercase letters, numbers, hyphens, and availability checks as
                  staff club creation.
                </p>
                <p
                  id={"convert-request-club-slug-feedback-#{@converting_request.request_id}"}
                  role="status"
                  aria-live="polite"
                  data-status={@conversion_slug_feedback.status}
                  class={ClubSlugForm.feedback_class(@conversion_slug_feedback)}
                >
                  {@conversion_slug_feedback.message}
                </p>
              </div>
              <div class="flex flex-wrap justify-end gap-2">
                <.button
                  id={"cancel-convert-request-#{@converting_request.request_id}"}
                  type="button"
                  phx-click="cancel_conversion"
                  variant="secondary"
                >
                  Cancel
                </.button>
                <.button
                  id={"confirm-convert-request-#{@converting_request.request_id}"}
                  type="submit"
                  disabled={not @conversion_slug_feedback.valid}
                >
                  Convert request
                </.button>
              </div>
            </.form>
          </div>
        </section>

        <section
          :if={@inactive_conversion_request_id}
          id="inactive-request-panel"
          class="rounded-xl border border-amber-200 bg-amber-50 p-5 text-amber-950 shadow-sm"
        >
          <h2 class="text-lg font-semibold">That request is no longer active.</h2>
          <p class="mt-2 text-sm leading-6">
            It may have already been converted or rejected, or the link may be wrong.
          </p>
          <div class="mt-4">
            <.button
              id="inactive-request-back-link"
              patch={~p"/admin/requests"}
              variant="secondary"
            >
              Back to active requests
            </.button>
          </div>
        </section>

        <.admin_table_card
          id="admin-requests-inbox-card"
          title="Active request inbox"
          description="Oldest active requests first, with the details staff need before rejection or conversion."
        >
          <div class="overflow-x-auto">
            <table
              id="admin-requests-table"
              aria-label="Active onboarding requests"
              class="min-w-full text-left text-sm"
            >
              <thead class="bg-[#efede8] text-xs font-bold uppercase tracking-[0.08em] text-[#7d877f]">
                <tr>
                  <th scope="col" class="px-4 py-3">Requester</th>
                  <th scope="col" class="px-4 py-3">Club</th>
                  <th scope="col" class="px-4 py-3">Note</th>
                  <th scope="col" class="px-4 py-3">Submitted</th>
                  <th scope="col" class="px-4 py-3">Actions</th>
                </tr>
              </thead>
              <tbody
                id="admin-requests"
                aria-label="Active requests"
                class="divide-y divide-[#e6e3dc]"
                phx-update="stream"
              >
                <tr id="admin-requests-empty" class="hidden only:table-row">
                  <td colspan="5" class="px-4 py-6 text-center text-sm text-[#7d877f]">
                    No active requests to review.
                  </td>
                </tr>
                <tr
                  :for={{dom_id, request} <- @streams.active_requests}
                  id={dom_id}
                  data-testid="admin-request-row"
                  data-request-id={request.request_id}
                  data-requested-club-name={request.requested_club_name}
                  aria-label={"Request for #{request.requested_club_name}"}
                  class="align-top transition-colors hover:bg-[#fbfaf8]"
                >
                  <td class="px-4 py-3.5">
                    <.admin_identity_cell
                      initials={requester_initials(request.requester_name)}
                      title={request.requester_name}
                      subtitle={request.requester_email}
                      testid="admin-request-requester"
                    />
                    <p class="mt-2 font-mono text-xs text-[#7d877f]">{request.request_id}</p>
                  </td>
                  <td class="px-4 py-3.5">
                    <div class="space-y-2">
                      <p
                        data-testid="admin-request-club"
                        class="font-semibold text-[#15201c]"
                      >
                        {request.requested_club_name}
                      </p>
                      <.status_badge label="Active" tone="info" />
                    </div>
                  </td>
                  <td
                    data-testid="admin-request-note"
                    class="max-w-md whitespace-pre-line px-4 py-3.5 leading-6 text-[#4b5a55]"
                  >
                    {request.note}
                  </td>
                  <td
                    data-testid="admin-request-submitted-at"
                    class="whitespace-nowrap px-4 py-3.5 text-[#4b5a55]"
                  >
                    {format_submitted_at(request.inserted_at)}
                  </td>
                  <td class="px-4 py-3.5">
                    <div data-testid="admin-request-actions" class="flex flex-wrap gap-2">
                      <.button
                        id={"reject-request-#{request.request_id}"}
                        type="button"
                        phx-click="start_rejection"
                        phx-value-request-id={request.request_id}
                        data-admin-request-action="reject"
                        data-request-id={request.request_id}
                        aria-label={"Reject request for #{request.requested_club_name}"}
                        variant="danger"
                      >
                        Reject
                      </.button>
                      <.button
                        id={"convert-request-#{request.request_id}"}
                        patch={~p"/admin/requests/#{request.request_id}"}
                        role="button"
                        data-admin-request-action="convert"
                        data-request-id={request.request_id}
                        aria-label={"Convert request for #{request.requested_club_name}"}
                      >
                        Convert
                      </.button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </.admin_table_card>
      </main>
    </Layouts.admin>
    """
  end

  defp assign_conversion_from_params(socket, request_id) do
    case active_request(request_id) do
      %Request{} = request ->
        params = conversion_params_from_request(request)

        socket
        |> clear_rejection()
        |> assign(:inactive_conversion_request_id, nil)
        |> assign(:converting_request, request)
        |> assign(:conversion_slug_autogenerated?, true)
        |> assign_conversion_form(params)

      nil ->
        socket
        |> clear_rejection()
        |> clear_conversion()
        |> assign(:inactive_conversion_request_id, request_id || "unknown")
        |> refresh_active_requests()
        |> put_flash(:error, "That request is no longer active.")
    end
  end

  defp assign_active_requests(socket, requests, opts \\ []) do
    stream_opts =
      [dom_id: &"request-row-#{&1.request_id}"]
      |> Keyword.merge(Keyword.take(opts, [:reset]))

    socket
    |> assign(:active_request_count, length(requests))
    |> stream(:active_requests, requests, stream_opts)
  end

  defp active_request(request_id) do
    case Onboarding.get_request(request_id) do
      %Request{} = request ->
        if request.status == Request.status_active(), do: request

      _request ->
        nil
    end
  end

  defp assign_rejection_form(socket, %Ecto.Changeset{} = changeset) do
    assign(socket, :rejection_form, to_form(changeset, as: :rejection))
  end

  defp assign_conversion_form(socket, club_params, target \\ []) do
    {club_params, slug_autogenerated?} =
      ClubSlugForm.suggest_params(
        club_params,
        target,
        socket.assigns.conversion_slug_autogenerated?
      )

    socket
    |> assign(:conversion_form, ClubSlugForm.to_form(club_params))
    |> assign(:conversion_slug_autogenerated?, slug_autogenerated?)
    |> assign(:conversion_slug_feedback, ClubSlugForm.feedback(nil, Map.get(club_params, "slug")))
  end

  defp clear_rejection(socket) do
    socket
    |> assign(:rejecting_request, nil)
    |> assign(:rejection_form, nil)
  end

  defp clear_conversion(socket) do
    socket
    |> assign(:converting_request, nil)
    |> assign(:conversion_form, nil)
    |> assign(:conversion_slug_autogenerated?, true)
    |> assign(:conversion_slug_feedback, ClubSlugForm.feedback(nil, ""))
  end

  defp request_no_longer_active(socket) do
    socket
    |> clear_rejection()
    |> clear_conversion()
    |> refresh_active_requests()
    |> put_flash(:error, "That request is no longer active.")
  end

  defp refresh_active_requests(socket) do
    assign_active_requests(socket, Onboarding.list_active_requests(), reset: true)
  end

  defp decrement_active_request_count(socket) do
    assign(socket, :active_request_count, max(socket.assigns.active_request_count - 1, 0))
  end

  defp assign_request_converted(socket, %{request: %Request{} = converted_request} = conversion) do
    socket
    |> clear_conversion()
    |> decrement_active_request_count()
    |> stream_delete(:active_requests, converted_request)
    |> push_patch(to: ~p"/admin/requests")
    |> put_flash(
      :info,
      "Converted request for #{converted_request.requested_club_name}."
    )
    |> maybe_put_welcome_email_flash(conversion)
  end

  defp maybe_put_welcome_email_flash(socket, %{welcome_email: :ok}), do: socket

  defp maybe_put_welcome_email_flash(socket, %{welcome_email: {:error, reason}}) do
    put_flash(socket, :error, "Welcome email could not be delivered: #{format_reason(reason)}")
  end

  defp maybe_put_welcome_email_flash(socket, _conversion), do: socket

  defp current_staff_email(socket) do
    socket.assigns.current_identity_email
  end

  defp conversion_params_from_request(%Request{} = request) do
    %{"name" => request.requested_club_name, "slug" => ""}
  end

  defp format_reason(%Ecto.Changeset{} = changeset) do
    changeset
    |> Ecto.Changeset.traverse_errors(fn {message, opts} ->
      Regex.replace(~r"%{(\w+)}", message, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
    |> inspect()
  end

  defp format_reason(reason), do: reason |> inspect() |> String.replace("_", " ")

  defp requester_initials(name) when is_binary(name) do
    name
    |> String.split(~r/\s+/, trim: true)
    |> Enum.take(2)
    |> Enum.map(&String.first/1)
    |> Enum.join()
    |> String.upcase()
    |> case do
      "" -> "RQ"
      initials -> initials
    end
  end

  defp requester_initials(_name), do: "RQ"

  defp format_submitted_at(%DateTime{} = inserted_at) do
    Calendar.strftime(inserted_at, "%Y-%m-%d %H:%M:%S UTC")
  end

  defp format_submitted_at(nil), do: "Unknown"
end
