defmodule MembaWeb.Admin.ClubSlugForm do
  @moduledoc """
  Shared staff club slug form behaviour.

  Staff club creation, staff club editing, and request-to-club conversion should
  use this module for slug suggestions, validation feedback, and availability
  checks so those workflows do not grow divergent slug rules.
  """

  alias Memba.Membership
  alias Memba.Membership.Slug

  @empty_params %{"name" => "", "slug" => ""}

  @doc """
  Returns the maximum supported staff-entered slug length.
  """
  def max_length, do: Slug.max_length()

  @doc """
  Empty params suitable for a new club form.
  """
  def empty_params, do: @empty_params

  @doc """
  Build a Phoenix form for the shared staff club fields.
  """
  def to_form(params \\ @empty_params) do
    params
    |> normalize_params()
    |> Phoenix.Component.to_form(as: :club)
  end

  @doc """
  Convert a projected club into shared form params.
  """
  def params_from_club(nil), do: @empty_params

  def params_from_club(%{name: name, slug: slug}) do
    %{"name" => name || "", "slug" => slug || ""}
  end

  @doc """
  Suggest or preserve a slug for live club form changes.

  The returned boolean records whether the slug is still auto-generated. Once
  staff edit the slug to a non-blank value, later name changes preserve their
  override.
  """
  def suggest_params(params, target, current_autogenerated?) when is_map(params) do
    slug_autogenerated? = slug_autogenerated?(params, target, current_autogenerated?)

    params =
      if slug_autogenerated? do
        Map.put(params, "slug", Slug.default_from_name(Map.get(params, "name", "")))
      else
        Map.put_new(params, "slug", "")
      end

    {params, slug_autogenerated?}
  end

  @doc """
  Return validation and availability feedback for a staff-entered slug.

  Pass the current club ID when editing an existing club so that club can keep
  its current slug. Pass `nil` for create or conversion forms where any
  projected club using the slug makes it unavailable.
  """
  def feedback(current_club_id, slug) do
    case Slug.validate(slug) do
      {:ok, valid_slug} ->
        availability_feedback(current_club_id, valid_slug)

      {:error, reason} ->
        %{
          status: "invalid",
          valid: false,
          message: invalid_slug_message(reason)
        }
    end
  end

  @doc """
  CSS class for staff slug feedback messages.
  """
  def feedback_class(%{status: "available"}), do: "mt-1 text-xs font-medium text-emerald-700"
  def feedback_class(%{status: "taken"}), do: "mt-1 text-xs font-medium text-red-700"
  def feedback_class(_feedback), do: "mt-1 text-xs font-medium text-amber-700"

  defp normalize_params(params) when is_map(params), do: Map.merge(@empty_params, params)
  defp normalize_params(_params), do: @empty_params

  defp slug_autogenerated?(params, target, current_autogenerated?) do
    case target || [] do
      ["club", "slug"] -> blank?(Map.get(params, "slug"))
      [] -> blank?(Map.get(params, "slug"))
      _target -> current_autogenerated?
    end
  end

  defp blank?(value) when is_binary(value), do: value == ""
  defp blank?(_value), do: true

  defp availability_feedback(current_club_id, slug) do
    case Membership.get_club_by_slug(slug) do
      nil ->
        available_slug_feedback()

      %{club_id: ^current_club_id} when is_binary(current_club_id) ->
        available_slug_feedback()

      _club ->
        %{
          status: "taken",
          valid: false,
          message: "This slug is already used by another club."
        }
    end
  end

  defp available_slug_feedback do
    %{
      status: "available",
      valid: true,
      message: "This slug is valid and available."
    }
  end

  defp invalid_slug_message(:blank), do: "Enter a slug."

  defp invalid_slug_message(:too_long),
    do: "Slug must be #{Slug.max_length()} characters or fewer."

  defp invalid_slug_message(_reason) do
    "Slug must use lowercase letters, numbers, and hyphens with no leading or trailing hyphen."
  end
end
